<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Australia</name>
   <tag></tag>
   <elementGuidId>5035bf1b-8354-4e1f-b67e-a45db0248818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div[4]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.navFooterLine.navFooterLinkLine.navFooterPadItemLine > ul > li.nav_first > a.nav_a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>845d321e-64cc-4ebc-a006-7750c991843f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com.au/ref=footer_au</value>
      <webElementGuid>73d8a3fd-f301-4826-97aa-31d3b140c564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>fb5171e8-ca19-458e-bc80-10c0d2204a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Australia</value>
      <webElementGuid>fd98cd33-448b-4680-9aec-4138c4c43042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterLine navFooterLinkLine navFooterPadItemLine&quot;]/ul[1]/li[@class=&quot;nav_first&quot;]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>2398b80c-8ee3-49f8-a467-75092d8bc11c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[4]/ul/li/a</value>
      <webElementGuid>dfc2e75c-f8fa-49d8-8c56-76fd760bf0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Australia')]</value>
      <webElementGuid>5f46a0a9-b838-44e3-93b4-b1ac2469fbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com.au/ref=footer_au')]</value>
      <webElementGuid>6d9f81c6-bef9-47c9-834a-3cc6b1ade9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a</value>
      <webElementGuid>bd99aa66-ec78-4a3c-ac02-5cc9e5727a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.com.au/ref=footer_au' and (text() = 'Australia' or . = 'Australia')]</value>
      <webElementGuid>a968e9c9-ffe7-4b19-98e7-0320879ddbfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
